import { hapTasks } from '@ohos/hvigor-ohos-plugin';
// @ts-ignore - Node.js built-in modules
const fs = require('fs');
// @ts-ignore - Node.js built-in modules
const path = require('path');

// Generate KeyCenterConfig.ets from env.json at build time
function generateKeyCenterConfig() {
  try {
    // Get current file directory (entry/)
    const entryDir = __dirname || path.dirname(process.argv[1] || '.');
    const projectRoot = path.resolve(entryDir, '..');
    const envFile = path.join(projectRoot, 'env.json');
    const outputFile = path.join(entryDir, 'src', 'main', 'ets', 'common', 'KeyCenterConfig.ets');
    
    let config: Record<string, string> = {};
    
    // Try to read env.json from project root
    if (fs.existsSync(envFile)) {
      try {
        const envContent = fs.readFileSync(envFile, 'utf-8');
        const envData = JSON.parse(envContent);
        config = envData;
        console.log('[hvigor] Loaded config from env.json');
      } catch (error) {
        console.warn(`[hvigor] Failed to parse env.json: ${error}`);
      }
    } else {
      console.warn(`[hvigor] env.json not found at ${envFile}, using empty config`);
    }
    
    // Escape single quotes and backslashes in config values
    const escapeValue = (value: string): string => {
      if (!value) return '';
      return String(value)
        .replace(/\\/g, '\\\\')  // Escape backslashes first
        .replace(/'/g, "\\'")    // Escape single quotes
        .replace(/\n/g, '\\n')   // Escape newlines
        .replace(/\r/g, '\\r');  // Escape carriage returns
    };
    
    // Generate TypeScript config file
    const configContent = `/**
 * Auto-generated configuration file
 * DO NOT EDIT THIS FILE MANUALLY
 * This file is generated from env.json at build time
 * 
 * ⚠️ SECURITY WARNING:
 * This file contains sensitive credentials and will be compiled into the app.
 * For production, consider using secure storage or fetching from server.
 */

export class KeyCenterConfig {
  static readonly APP_ID: string = '${escapeValue(config.appId || '')}';
  static readonly APP_CERTIFICATE: string = '${escapeValue(config.appCertificate || '')}';
  static readonly REST_KEY: string = '${escapeValue(config.restKey || '')}';
  static readonly REST_SECRET: string = '${escapeValue(config.restSecret || '')}';
  static readonly PIPELINE_ID: string = '${escapeValue(config.pipelineId || '')}';
}
`;
    
    // Ensure output directory exists
    const outputDir = path.resolve(outputFile, '..');
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }
    
    fs.writeFileSync(outputFile, configContent, 'utf-8');
    console.log(`[hvigor] Generated KeyCenterConfig.ets`);
  } catch (error) {
    console.error(`[hvigor] Failed to generate KeyCenterConfig: ${error}`);
  }
}

// Generate config before build
generateKeyCenterConfig();

export default {
  system: hapTasks, /* Built-in plugin of Hvigor. It cannot be modified. */
  plugins: []       /* Custom plugin to extend the functionality of Hvigor. */
}