/**
 * Generate KeyCenter.ts from .env file at build time
 * This script reads .env file and generates TypeScript configuration
 */

const fs = require('fs');
const path = require('path');

function generateKeyCenterConfig() {
  try {
    // Get project root (parent directory of scripts/)
    const scriptDir = __dirname || path.dirname(process.argv[1] || '.');
    const projectRoot = path.resolve(scriptDir, '..');
    const envFile = path.join(projectRoot, '.env');
    const outputFile = path.join(projectRoot, 'src', 'utils', 'KeyCenterConfig.ts');
    
    let config = {
      AGORA_APP_ID: '',
      AGORA_APP_CERTIFICATE: '',
      AGORA_REST_KEY: '',
      AGORA_REST_SECRET: '',
      AGORA_PIPELINE_ID: '',
    };
    
    // Try to read .env file
    if (fs.existsSync(envFile)) {
      try {
        const envContent = fs.readFileSync(envFile, 'utf-8');
        const lines = envContent.split('\n');
        
        lines.forEach((line) => {
          // Skip comments and empty lines
          const trimmedLine = line.trim();
          if (trimmedLine && !trimmedLine.startsWith('#')) {
            const match = trimmedLine.match(/^([^=]+)=(.*)$/);
            if (match) {
              const key = match[1].trim();
              const value = match[2].trim().replace(/^["']|["']$/g, ''); // Remove quotes
              
              // Map .env keys to config keys
              if (key === 'AGORA_APP_ID') {
                config.AGORA_APP_ID = value;
              } else if (key === 'AGORA_APP_CERTIFICATE') {
                config.AGORA_APP_CERTIFICATE = value;
              } else if (key === 'AGORA_REST_KEY') {
                config.AGORA_REST_KEY = value;
              } else if (key === 'AGORA_REST_SECRET') {
                config.AGORA_REST_SECRET = value;
              } else if (key === 'AGORA_PIPELINE_ID') {
                config.AGORA_PIPELINE_ID = value;
              }
            }
          }
        });
        
        console.log('[generate-config] Loaded config from .env');
      } catch (error) {
        console.warn(`[generate-config] Failed to parse .env: ${error.message}`);
      }
    } else {
      console.warn(`[generate-config] .env not found at ${envFile}, using empty config`);
    }
    
    // Escape single quotes and backslashes in config values
    const escapeValue = (value) => {
      if (!value) return '';
      return String(value)
        .replace(/\\/g, '\\\\')  // Escape backslashes first
        .replace(/'/g, "\\'")   // Escape single quotes
        .replace(/\n/g, '\\n')  // Escape newlines
        .replace(/\r/g, '\\r'); // Escape carriage returns
    };
    
    // Generate TypeScript config file
    const configContent = `/**
 * Auto-generated configuration file
 * DO NOT EDIT THIS FILE MANUALLY
 * This file is generated from .env at build time
 * 
 * ⚠️ SECURITY WARNING:
 * This file contains sensitive credentials and will be compiled into the app.
 * For production, consider using secure storage or fetching from server.
 * 
 * To regenerate this file, run: npm run generate-config
 */

export class KeyCenterConfig {
  static readonly AGORA_APP_ID: string = '${escapeValue(config.AGORA_APP_ID)}';
  static readonly AGORA_APP_CERTIFICATE: string = '${escapeValue(config.AGORA_APP_CERTIFICATE)}';
  static readonly REST_KEY: string = '${escapeValue(config.AGORA_REST_KEY)}';
  static readonly REST_SECRET: string = '${escapeValue(config.AGORA_REST_SECRET)}';
  static readonly PIPELINE_ID: string = '${escapeValue(config.AGORA_PIPELINE_ID)}';
}
`;
    
    // Ensure output directory exists
    const outputDir = path.dirname(outputFile);
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }
    
    fs.writeFileSync(outputFile, configContent, 'utf-8');
    console.log(`[generate-config] Generated KeyCenterConfig.ts`);
  } catch (error) {
    console.error(`[generate-config] Failed to generate KeyCenter.ts: ${error.message}`);
    process.exit(1);
  }
}

// Run if called directly
if (require.main === module) {
  generateKeyCenterConfig();
}

module.exports = { generateKeyCenterConfig };

