# Script to validate KeyCenter.h configuration
# Always exits with 0 to allow compilation (errors shown via #error directive)

# Suppress errors - we handle them gracefully
$ErrorActionPreference = "Continue"

try {
    # Determine project paths
    $ScriptDir = Split-Path -Parent $PSCommandPath
    $ProjectRoot = Split-Path -Parent $ScriptDir
    $KeyCenterFile = Join-Path $ProjectRoot "VoiceAgent\src\KeyCenter.h"
    $TemplateFile = Join-Path $ProjectRoot "KeyCenter.h.example"
    
    Write-Host "🔍 Checking KeyCenter.h..." -ForegroundColor Cyan
    
    # Function to create error header with #error directive
    function Create-ErrorHeader {
        param([string]$Message, [string]$Steps)
        
        $Content = @"
#pragma once

/*
╔══════════════════════════════════════════════════════════════════════════╗
║                                                                          ║
║  ⚠️  CONFIGURATION REQUIRED: KeyCenter.h                                ║
║                                                                          ║
╚══════════════════════════════════════════════════════════════════════════╝

ERROR: $Message

NEXT STEPS:
$Steps

Get your credentials from: https://console.agora.io/

After configuration, rebuild the project.

*/

#error "⚠️  KeyCenter.h needs configuration. $Message Read the comments above for instructions."

// This file was auto-generated by check_keycenter.ps1
// Delete this file and follow the instructions above to configure your credentials
"@
        
        try {
            $KeyCenterDir = Split-Path -Parent $KeyCenterFile
            if (-not (Test-Path $KeyCenterDir)) {
                New-Item -ItemType Directory -Path $KeyCenterDir -Force | Out-Null
            }
            Set-Content -Path $KeyCenterFile -Value $Content -Encoding UTF8 -Force
            Write-Host "✓ Created error header at: $KeyCenterFile" -ForegroundColor Yellow
            return $true
        }
        catch {
            Write-Host "✗ Failed to create error header: $_" -ForegroundColor Red
            return $false
        }
    }
    
    # Check if KeyCenter.h exists
    if (-not (Test-Path $KeyCenterFile)) {
        Write-Host "⚠️  KeyCenter.h not found" -ForegroundColor Yellow
        
        $Steps = @"
  1. Copy the template file:
     From: $TemplateFile
     To:   $KeyCenterFile
  
  2. Edit $KeyCenterFile and replace these values:
     • YOUR_APP_ID_HERE       → Your Agora App ID
     • YOUR_REST_KEY_HERE     → Your REST API Key  
     • YOUR_REST_SECRET_HERE  → Your REST API Secret
     • YOUR_PIPELINE_ID_HERE  → Your Pipeline ID
  
  3. Save the file and rebuild
"@
        
        Create-ErrorHeader -Message "KeyCenter.h file is missing" -Steps $Steps
        exit 0
    }
    
    # Read KeyCenter.h content
    $Content = Get-Content $KeyCenterFile -Raw -ErrorAction SilentlyContinue
    
    if (-not $Content) {
        Write-Host "⚠️  KeyCenter.h is empty or unreadable" -ForegroundColor Yellow
        $Steps = @"
  1. Delete the empty KeyCenter.h file
  2. Copy from template: $TemplateFile
  3. Configure your credentials
  4. Rebuild
"@
        Create-ErrorHeader -Message "KeyCenter.h is empty or corrupted" -Steps $Steps
        exit 0
    }
    
    # Check if it's already an error header (from previous run)
    if ($Content -match "#error") {
        Write-Host "⚠️  KeyCenter.h contains configuration error" -ForegroundColor Yellow
        Write-Host "   Check the Error List after build for instructions" -ForegroundColor Gray
        exit 0
    }
    
    # Validate configuration
    if ($Content -match "YOUR_APP_ID_HERE") {
        Write-Host "⚠️  KeyCenter.h contains placeholder values" -ForegroundColor Yellow
        
        $Steps = @"
  1. Open file: $KeyCenterFile
  
  2. Replace ALL placeholder values:
     • YOUR_APP_ID_HERE       → Your actual Agora App ID
     • YOUR_REST_KEY_HERE     → Your REST API Key
     • YOUR_REST_SECRET_HERE  → Your REST API Secret
     • YOUR_PIPELINE_ID_HERE  → Your Pipeline ID
  
  3. Get credentials from: https://console.agora.io/
  
  4. Save and rebuild
"@
        
        Create-ErrorHeader -Message "KeyCenter.h contains placeholder values (not configured yet)" -Steps $Steps
        exit 0
    }
    
    # Check for empty App ID
    if ($Content -match 'AGORA_APP_ID\s*=\s*""') {
        Write-Host "⚠️  AGORA_APP_ID is empty" -ForegroundColor Yellow
        
        $Steps = @"
  1. Open: $KeyCenterFile
  
  2. Set AGORA_APP_ID to your actual App ID (not empty string)
  
  3. Get App ID from: https://console.agora.io/
  
  4. Save and rebuild
"@
        
        Create-ErrorHeader -Message "AGORA_APP_ID is empty string" -Steps $Steps
        exit 0
    }
    
    # All checks passed
    Write-Host "✅ KeyCenter.h is properly configured" -ForegroundColor Green
    exit 0
}
catch {
    # If script crashes for any reason, still exit 0 but log the error
    Write-Host "⚠️  Script error: $_" -ForegroundColor Red
    Write-Host "   Continuing build..." -ForegroundColor Gray
    exit 0
}
