# Uncomment the next line to define a global platform for your project
# platform :ios, '17.0'

target 'VoiceAgent' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VoiceAgent
  pod 'AgoraRtcEngine_iOS', '4.5.1'
  pod 'AgoraRtm', :path => 'AgoraRtm.podspec'
  pod 'AlertToast'

end
