package io.agora.convoai.example.startup.api;

import io.agora.convoai.example.startup.KeyCenter;
import io.agora.convoai.example.startup.api.net.SecureOkHttpClient;
import io.agora.convoai.example.startup.tools.Base64Encoding;
import okhttp3.MediaType;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

/**
 * Agent Starter
 * Unified interface for starting/stopping agents
 * Only the base URL differs between local server and Agora API
 */
public class AgentStarter {
    private static final String JSON_MEDIA_TYPE = "application/json; charset=utf-8";
    
    // Switch between local server and Agora API by commenting/uncommenting the lines below
    
    // Option 1: Agora RESTful API (Default, for quick experience)
    private static final String AGORA_API_BASE_URL = "https://api.sd-rtn.com/cn/api/conversational-ai-agent/v2/projects";
    
    // Option 2: Local Python Server (For development testing reference)
    // private static final String AGORA_API_BASE_URL = "http://<YOUR_COMPUTER_IP>:8080";

    private static final String DEFAULT_AGENT_RTC_UID = "1009527";

    private static final OkHttpClient okHttpClient = SecureOkHttpClient.create().build();
    private static final ExecutorService executorService = Executors.newCachedThreadPool();

    /**
     * Start an agent
     * Unified interface: same format for both local server and Agora API
     *
     * @param channelName Channel name for the agent
     * @param agentRtcUid Agent RTC UID (optional, defaults to "1009527")
     * @param token Agent token (required, should be generated by client)
     * @param callback Callback for result
     */
    public static void startAgentAsync(
        String channelName,
        String agentRtcUid,
        String token,
        AgentStartCallback callback
    ) {
        executorService.execute(() -> {
            try {
                String projectId = KeyCenter.AGORA_APP_ID;
                String url = AGORA_API_BASE_URL + "/" + projectId + "/join/";

                List<String> remoteRtcUids = new ArrayList<>();
                remoteRtcUids.add("*");
                JSONObject requestBody = buildJsonPayload(
                    channelName,
                    KeyCenter.PIPELINE_ID,
                    channelName,
                    agentRtcUid,
                    token,
                    remoteRtcUids
                );

                Request.Builder requestBuilder = new Request.Builder()
                    .url(url)
                    .addHeader("Content-Type", JSON_MEDIA_TYPE)
                    .post(RequestBody.create(
                        requestBody.toString(),
                        MediaType.parse(JSON_MEDIA_TYPE)
                    ));

                // Add Authorization header
                String authorization = Base64Encoding.gen(KeyCenter.REST_KEY, KeyCenter.REST_SECRET);
                requestBuilder.addHeader("Authorization", authorization);

                Request request = requestBuilder.build();
                Response response = okHttpClient.newCall(request).execute();

                if (!response.isSuccessful()) {
                    String errorBody = response.body() != null ? response.body().string() : response.message();
                    throw new RuntimeException("Start agent error: httpCode=" + response.code() + ", httpMsg=" + errorBody);
                }

                String body = response.body() != null ? response.body().string() : null;
                if (body == null) {
                    throw new RuntimeException("Response body is null");
                }

                JSONObject bodyJson = new JSONObject(body);

                // Unified response format: {"agent_id": "..."}
                String agentId = bodyJson.optString("agent_id", "");

                if (agentId.isEmpty()) {
                    throw new RuntimeException("Failed to parse agentId from response: " + body);
                }

                callback.onSuccess(agentId);
            } catch (Exception e) {
                callback.onFailure(e);
            }
        });
    }

    /**
     * Start an agent with default agent RTC UID
     */
    public static void startAgentAsync(
        String channelName,
        String token,
        AgentStartCallback callback
    ) {
        startAgentAsync(channelName, DEFAULT_AGENT_RTC_UID, token, callback);
    }

    /**
     * Build JSON payload for Agora API
     */
    private static JSONObject buildJsonPayload(
        String name,
        String pipelineId,
        String channel,
        String agentRtcUid,
        String token,
        List<String> remoteRtcUids
    ) throws JSONException {
        Map<String, Object> payloadMap = new HashMap<>();
        payloadMap.put("name", name);
        payloadMap.put("pipeline_id", pipelineId);
        
        Map<String, Object> properties = new HashMap<>();
        properties.put("channel", channel);
        properties.put("agent_rtc_uid", agentRtcUid);
        properties.put("remote_rtc_uids", remoteRtcUids);
        properties.put("token", token);
        payloadMap.put("properties", properties);
        
        return mapToJsonObjectWithFilter(payloadMap);
    }

    /**
     * Convert Map to JSONObject, filtering out null values
     */
    private static JSONObject mapToJsonObjectWithFilter(Map<String, Object> map) throws JSONException {
        JSONObject jsonObject = new JSONObject();
        for (Map.Entry<String, Object> entry : map.entrySet()) {
            String key = entry.getKey();
            Object value = entry.getValue();
            
            if (value == null) {
                // Skip null values
                continue;
            } else if (value instanceof Map) {
                // Handle nested Map
                @SuppressWarnings("unchecked")
                JSONObject nestedJsonObject = mapToJsonObjectWithFilter((Map<String, Object>) value);
                if (nestedJsonObject.length() > 0) {
                    jsonObject.put(key, nestedJsonObject);
                }
            } else if (value instanceof List) {
                // Handle List type
                JSONArray jsonArray = new JSONArray();
                for (Object item : (List<?>) value) {
                    if (item == null) {
                        // Skip null values
                        continue;
                    } else if (item instanceof Map) {
                        // Handle Map in List
                        @SuppressWarnings("unchecked")
                        JSONObject itemJsonObject = mapToJsonObjectWithFilter((Map<String, Object>) item);
                        jsonArray.put(itemJsonObject);
                    } else {
                        jsonArray.put(item);
                    }
                }
                if (jsonArray.length() > 0) {
                    jsonObject.put(key, jsonArray);
                }
            } else {
                // Handle basic types
                jsonObject.put(key, value);
            }
        }
        return jsonObject;
    }

    /**
     * Stop an agent
     * Unified interface: same format for both local server and Agora API
     *
     * @param agentId Agent ID to stop
     * @param callback Callback for result
     */
    public static void stopAgentAsync(String agentId, AgentStopCallback callback) {
        executorService.execute(() -> {
            try {
                String projectId = KeyCenter.AGORA_APP_ID;
                String url = AGORA_API_BASE_URL + "/" + projectId + "/agents/" + agentId + "/leave";

                Request.Builder requestBuilder = new Request.Builder()
                    .url(url)
                    .post(RequestBody.create("", MediaType.parse("application/json; charset=utf-8")));

                // Add Authorization header
                String authorization = Base64Encoding.gen(KeyCenter.REST_KEY, KeyCenter.REST_SECRET);
                requestBuilder.addHeader("Authorization", authorization);

                Request request = requestBuilder.build();
                Response response = okHttpClient.newCall(request).execute();

                if (!response.isSuccessful()) {
                    String errorBody = response.body() != null ? response.body().string() : response.message();
                    throw new RuntimeException("Stop agent error: httpCode=" + response.code() + ", httpMsg=" + errorBody);
                }

                // Unified response: just check status code
                if (response.body() != null) {
                    response.body().close();
                }

                callback.onSuccess();
            } catch (Exception e) {
                callback.onFailure(e);
            }
        });
    }

    /**
     * Check if the server is available
     *
     * @param callback Callback for result
     */
    public static void checkServerHealth(ServerHealthCallback callback) {
        executorService.execute(() -> {
            try {
                // Health check only works for local server
                // For Agora API, skip health check or use a different endpoint
                if (AGORA_API_BASE_URL.startsWith("http://")) {
                    String url = AGORA_API_BASE_URL + "/health";
                    Request request = new Request.Builder()
                        .url(url)
                        .get()
                        .build();
                    Response response = okHttpClient.newCall(request).execute();
                    callback.onResult(response.isSuccessful());
                } else {
                    // Agora API doesn't have a health endpoint, return success
                    callback.onResult(true);
                }
            } catch (Exception e) {
                callback.onFailure(e);
            }
        });
    }

    /**
     * Callback interface for agent start operation
     */
    public interface AgentStartCallback {
        void onSuccess(String agentId);
        void onFailure(Exception exception);
    }

    /**
     * Callback interface for agent stop operation
     */
    public interface AgentStopCallback {
        void onSuccess();
        void onFailure(Exception exception);
    }

    /**
     * Callback interface for server health check
     */
    public interface ServerHealthCallback {
        void onResult(boolean isAvailable);
        void onFailure(Exception exception);
    }
}
